[package]
name = "sddl"
version = "0.0.8"
edition = "2021"
authors = ["Jan Starke <jan.starke@posteo.de>"]
license = "GPL-3.0"
readme = "README.md"
documentation = "https://docs.rs/sddl"
repository = "https://github.com/janstarke/sddl"
description = "a library to parse and analyse SDDL Strings"


[dependencies]
binrw = "0.14.0"
bitflags = "2.6.0"
getset = "0"
strum = {version="0", features=["derive"]}
thiserror = "1.0.64"
uuid = {version="1.6", features=["serde", "v4"]}
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
lazy_static = "1.5"
lazy-regex = "3"
derivative = "2.2"

[build-dependencies]
lazy-regex = "3"
lalrpop = "0.22.0"