[package]
name = "sddl"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.0"
bitflags = "2.6.0"
getset = "0"
strum = {version="0", features=["derive"]}
uuid = {version="1.6", features=["serde", "v4"]}
