[package]
name = "sddl"
version = "0.0.1"
edition = "2021"
authors = ["Jan Starke <jan.starke@posteo.de>"]
license = "GPL-3.0"
readme = "README.md"
documentation = "https://docs.rs/sddl"
repository = "https://github.com/janstarke/sddl"
description = "a library to parse and analyse SDDL Strings"


[dependencies]
binrw = "0.14.0"
bitflags = "2.6.0"
getset = "0"
strum = {version="0", features=["derive"]}
uuid = {version="1.6", features=["serde", "v4"]}

[build-dependencies]
lazy-regex = "3"